### ISSUE TITLE
git checkout and the working tree

### ISSUE THREAD

**Issue by jennybc** [jennybc/githug#10]
I'm pretty sure I should be checking if working tree is clean/dirty and .... do something. Or can I just let `git2r/libgit2` deal with it? That would be nice.

**Comment by gaborcsardi** [comment]
I think this maybe makes sense before some operations. E.g. rebase, pull, although I have no idea what libgit2 does if it cannot merge a pull.

**Comment by jennybc** [comment]
I have done some things via `githug` that my usual git client does not allow, which is how I started to worry about this. 🤔

**Comment by jennybc** [comment]
In the reboot, I've gotten more deeply into this and I now think I was confused about `git2r`. AFAICT it behaves like command line fit w/r/t checkouts and overwriting.
