### ISSUE TITLE
printing of data frames that contain list-columns of S4 objects

### ISSUE THREAD

**Issue by jennybc** [jennybc/githug#3]
I might need to do something so that printing works even if `dplyr` is not loaded.

https://github.com/ropensci/git2r/issues/215

http://stackoverflow.com/questions/34731771/printing-a-data-frame-that-contains-a-list-column-of-s4-objects

Work around posted in a now-vanished comment by SO user rawr:

``` r
library(Matrix)
m <- new("dgCMatrix")
df <- data.frame(id = 1:2)
df$matrices <- list(m, m)
df[] <- lapply(df, as.character)
df
#>   id                         matrices
#> 1  1 <S4 object of class "dgCMatrix">
#> 2  2 <S4 object of class "dgCMatrix">
```

**Comment by jennybc** [comment]
Not a problem in the reboot. The tibble/dplyr world has evolved and because I depend on purrr, I indirectly depend on dplyr 😕.

**Comment by ijlyttle** [comment]
Could it be useful to import tbl_df() directly from tibble, then export?

Every so often, I find myself going back to this Ramnath SO [answer](http://stackoverflow.com/questions/27947344/r-use-magrittr-pipe-operator-in-self-written-package#comment56720179_27979637) where he points to this ggvis [example](https://github.com/rstudio/ggvis/blob/master/R/pipe.R).

**Comment by jennybc** [comment]
I'm not having any printing troubles now. Since I originally opened this, the `tibble` package came into being and its print method for `tbl_df`s seems to get the job done here in the reboot. Let me know if I've misunderstood you or if you've tried the new githug out and you see a problem.

**Comment by ijlyttle** [comment]
It is me who has misunderstood - not recognizing (or even thinking to recognize) the difference between a print method and returning a tibble for interactive use.

Sorry for the needless distraction.

**Comment by jennybc** [comment]
Not a problem!
